sudo: false
addons:
  apt:
    packages:
      - curl
      - make
      - libgc-dev
      - ruby1.9.1-dev

before_install:
  - git clone --depth=1 git://github.com/nddrylliog/rock.git 
  - (cd rock && make -s quick-rescue)
  - export PATH=$PATH:$PWD/rock/bin

script:
  - export OOC_LIBS=$PWD
  - cd samples/test
  - mkdir -p travis
  - rock -v test && ./test


notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always


